### ISSUE TITLE
viewer: allow pinch-to-zoom when viewing pictures

### ISSUE THREAD

**Issue by pacien** [pacien/ldgallery#106]
~~The UX is terrible. It could be heavily simplified by using the mouse wheel on desktop and pinch on mobile to zoom in and out on pictures. A double click or double tap could trigger the full screen view instead of a simple click and tap.~~ Most is solved by #195. Only pinch-to-zoom is missing.

**Comment by OzoneGrif** [comment]
That's not a bug, that's a feature. Please don't criticize features which have not been implemented yet. This is not pleasant. <.<
