### ISSUE TITLE
Empty YAML tag crash with an error

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#122]
LoadException "test.jpg.yaml" (AesonException "Error in $.tags[0]: expected String, but encountered Null")

To simplify YAML templating, a null tag (or empty string) should be ignored and dropped by the compiler.

The template looks like this:
```
title: Test.png 
 
datetime: 
 
description: 
 
tags: 
  - 
```

**Comment by OzoneGrif** [comment]
Got a better idea.

**Comment by pacien** [comment]
This sidecar file is invalid and the rejection is the desired behaviour.

You may specify an empty list of tags as follows:

```yaml
tags: []
```
