### ISSUE TITLE
`index.json` contains redundant tag data

### ISSUE THREAD

**Issue by pacien** [pacien/ldgallery#134]
The generated `index.json` lists item tags in a redundant manner: they are both aggregated upwards from items and propagated downwards for directories. Since the viewer is already indexing the stucture for counting tags, there's no point in doing this at the compilation step.

**Comment by OzoneGrif** [comment]
I'm not sure about that one. The fact that directories aggregate the tags may be useful in the future. I see opportunities to use this information for algorithm improvements. I suggest not touching this feature for now.

**Comment by pacien** [comment]
It might be reasonable to assume that compression could handle this kind of repetition quite well, making the removal of those data not that useful. Let's verify that assumption empirically on some test galleries.

Disabling aggregation is roughly equivalent to stripping the tags array on directory items:

```shell
jq -c \
  'walk(if type == "object" and .properties.type == "directory" then .tags = [] else . end)'  \
  index.json > index_stripped.json
```

Comparing the original and compressed (with `gzip -1`) versions of gallery indexes yields:

| Input gallery | Number of items | Original index size | Stripped index size | Original index compressed size | Stripped index compressed size |
| - | - | - | - | - | - |
| A | 300 | 230KB | 210KB | 43KB | 39KB |
| B | 4000 | 1775KB | 1772KB | 131KB | 131KB |

That's a 10% reduction on the compressed size of the index of gallery A, and no noticeable difference for gallery B. However, since the compressed indexes are of sizes in the order of kilobytes, the savings are negligible compared to the actual content of the galleries.

As you suggested, this aggregated information could be useful when searching through the index, for example by allowing to stop early when searching down the index tree. Let's keep the index as is, with the aggregated and propagated tags.
