### ISSUE TITLE
viewer: top of tag suggestions is displayed "under" the filter field

### ISSUE THREAD

**Issue by pacien** [pacien/ldgallery#183]
When the tag suggestion list is long and the viewport small, the top of the suggestions slips "under" the filter input field and buttons:

![15861328036861](https://user-images.githubusercontent.com/1449319/78513785-47bffa00-77ae-11ea-86c6-13283750d801.png)

**Comment by OzoneGrif** [comment]
You want the title "Related filters" to stay visible at all times?

**Comment by pacien** [comment]
Look more carefully at the screenshot: it's partially covered despite not being in the scrollable part.
Parts of the scrollable content also gets hidden in some cases, making their top part unreachable.
