### ISSUE TITLE
viewer: v-dragscroll issue with touchpad on some components

### ISSUE THREAD

**Issue by pacien** [pacien/ldgallery#185]
Some components use the `v-dragscroll` property without actually needing it, as they already have a scrollbar on desktop, hence the implicit drag scroll support on mobile. This drag-to-scroll behaviour is rather unsettling on desktop, preventing the selection of text, in the "related filters" panel in particular.

**Comment by OzoneGrif** [comment]
I actually like the unification of both scroll methods and use it even on desktop.
The question is more about text selection. 
What are the use cases where you would need to select text?

**Comment by pacien** [comment]
> I actually like the unification of both scroll methods and use it even on desktop.

It's ok for the picture viewer but it's just awful for lists.

The scroll direction goes in the opposite way as with the scrollbar, which is just annoying when clicking next to it with a mouse.

Touchpads are also badly impacted by this due to the tap-to-click and movements being registered as a scroll event when they shouldn't. Touchpads already support side and multitouch scrolls.

> The question is more about text selection.
> What are the use cases where you would need to select text?

Copying someone's name for instance.
It's text and it's really frustrating for the user to have arbitrary restrictions on what they can do.
