### ISSUE TITLE
viewer: tag categories proposed again in "other filters"

### ISSUE THREAD

**Issue by pacien** [pacien/ldgallery#186]
With gallery.yaml:
```yaml
tagCategories:
  - photographer
  - location
```

Those tag categories are still showing in "other filters".

![15861388821293](https://user-images.githubusercontent.com/1449319/78517100-472e6000-77bc-11ea-9ef8-95b93563be01.png)

I remember from our previous discussion that we wanted the tag categories not to be proposed in the suggestions, and to stay available only in the auto-completion when being typed in the query field.

**Comment by OzoneGrif** [comment]
Yep, it was actually a question because it was difficult to do at first.
Since the upgrade of the index with new information, it was actually easy to do.
Categories are available in the "Other filters" section now.

**Comment by pacien** [comment]
Can we hide them from the "other filters" category? They just push relevant tags further down for little benefit. If the user still wants to filter items having those categories, it's still possible to do so by typing those in the filter input field.
