### ISSUE TITLE
website: add OpenGraph meta-tags

### ISSUE THREAD

**Issue by zeroinformatique** [pacien/ldgallery#263]
The website doesn't display any information when linked through social media websites. We should add OpenGraph tags and a picture:
https://ogp.me/

**Comment by pacien** [comment]
Despite the name beginning with "Open", this is a Facebook-specific thing.
It's also designed for the generation of content cards (like a specific movie on a review website), not general website previews.

I went ahead and added a standard meta description tag instead, which should assist them generating the latter correctly.
