### ISSUE TITLE
viewer: configurable gallery url

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#32]
config.json right next to index.html
must describe:
* The compilation date/or/timestamp
* The gallery's URL (default: "gallery/")

Might be used later for theme colors and other styles or components

**Comment by pacien** [comment]
The compiler generates the `config.json` files when generating a gallery with the `--with-viewer` flag.

@OzoneGrif The viewer now needs to read that file to know which gallery to load.
