### ISSUE TITLE
Category for folder tags

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#59]
Folders are tagged individually without a category which make them difficult to identify.

Store the folders tags in their own category

"folders": [
	"Photos",
	"UK-Ireland-2017"
],
"tags": [ .. ]

**Comment by pacien** [comment]
The proposed structure doesn't make sense, and this information is already contained within the tree structure.

__Please explain the necessity for the separate handling of folder names.__

Recall that the tags derived from folders with the `compiler.tagsFromDirectories` option is only offered for convenience for those who don't want to tag individual items within a directory. It cannot be a substitute for proper tagging.

**Comment by OzoneGrif** [comment]
This is a required functionality, not a "convenience".

Users have to be able to filter their search by folders (ie "folder:france"). Currently, there are no discriminant for the folder tags (ie "france"). At first, I requested a prefix, but you didn't like the idea and preferred to store these special tags in their own category. I don't mind either one, but the fact is we need something to discriminate the folder tags from normal, user tags.
