### ISSUE TITLE
Apply the EXIF rotation to the thumbnail (and remove the EXIF). Also apply the rotation to the item in case of resizing (but not copying).

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#67]
FireFox and Chrome will handle the CSS image-orientation soon, there are still issues:
- It doesn't work for background image (which I use in the viewer now to preview the picture being loaded)
- It doesn't work for negative rotations (occurs on some photos)

There is also an unrelated issue on FireFox:
- Some pictures' canvas appear white while loading, instead of transparent. Not all pictures are affected, and this is only on FireFox. I suspect a flag in the EXIF color/transparency data.

**Comment by pacien** [comment]
I can rotate thumbnails when generating them, however I cannot touch the full images when they don't need to be resized. Could you confirm that you only need the thumbnails to be pre-rotated?

**Comment by OzoneGrif** [comment]
Do the thumbnail first. We'll see for the whole picture depending on Chrome v81
