### ISSUE TITLE
"unsafe-inline" on SVG icons

### ISSUE THREAD

**Issue by pacien** [pacien/ldgallery#69]
A sane/strict Content-Security-Policy not allowing 'unsafe-inline' breaks the rendering of the SVG icons in the viewer. Those forbidden unsafe-inline should be avoided one way or the other.

![15804766471533](https://user-images.githubusercontent.com/1449319/73542278-9e1e5e80-4434-11ea-8474-c840b13e1f00.png)

**Comment by OzoneGrif** [comment]
Resolved in be8ec3edaed843f08dac3d2bf2f10f7247ef3d3a
