### ISSUE TITLE
excludedDirectories doesn't work

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#71]
I won't to exclude all `Thumbs.db` directories from the output. These are generated by Windows' Explorer and can't be deleted easily.

I tried everything: RegEx, Relative Path, Absolute Path, with slash, anti-slash; nothing worked.

**Comment by pacien** [comment]
I'm unable to reproduce this (on Linux).

I created a directory named "Thumbs.db" inside of my gallery source dir and added the following to my gallery.conf:

```yaml
compiler:
  excludedDirectories:
    - Thumbs.db
```

The compiler is indeed excluding those directories when generating the gallery.

**Comment by OzoneGrif** [comment]
`compiler:
  galleryName: Ozone's Private gallery

#  includedDirectories: ["*"]

  excludedDirectories:
  - Thumbs.db

  includedFiles:
  - "*.*"

  excludedFiles:
  - ".*"
  - "*.html*"

  tagsFromDirectories: 2

  thumbnailMaxResolution:
    width: 250  # default
    height: 250 # default

#  pictureMaxResolution:
#    width: 9999
#    height: 9999

  #jpegExportQuality: 80 # default


viewer: {}
`
Results in:
`{
	"title": "Thumbs.db",
	"datetime": "2020-01-19T02:49:52.095Z",
	"description": "",
	"tags": [],
	"path": "/Thumbs.db",
	"thumbnail": null,
	"properties": {
		"type": "other",
		"resource": "items/Thumbs.db?1580482340"
	}
},
`

**Comment by pacien** [comment]
`"type": "other"` tells me that those "Thumbs.db" are files, not directories.
Could you try moving the exclusion rule to `excludedFiles`?

**Comment by OzoneGrif** [comment]
Pff, tell me to go to bed. 😴
