### ISSUE TITLE
compiler: cache derived item properties

### ISSUE THREAD

**Issue by OzoneGrif** [pacien/ldgallery#97]
Magick is called to recover the picture's sizes even though this information has already been parsed by a previous compilation, and the files didn't change.

Find a way to reuse former resolution data, either by reloading index.json and use its data when skipping files, or generate another cache file specific to the compiler.

**Comment by pacien** [comment]
Caching derived item properties will indeed be very important especially if we want to support audio and video files (#158) or use BlurHash for thumbnails (#174).
